### ISSUE TITLE
고려해볼 적용사항들

### ISSUE THREAD

**Issue by donsonioc2010** [NC7-BleuAuction/bleuauction_be#143]
1. LAZY관계들 성능최적화
2. 모놀리식 -> 멀티모듈
3. 현재 Request, Response에서 받는 Entity를 개별의 DTO로 변경하여 파라미터로 받고, 응답하게 변경
4. TestCase Coverage
5. 조회를 QueryDSL로 변경
6. 부하테스트
7. Java To Kotlin

일단 이정도가 생각이 드네요 할게 많아유 파이팅

생각해보니, 실제 API테스트시 Entity를 Response로 반환하는 기능은 오류가 날것 같습니다.
Jackson라이브러리에서 반환할 떄 서로가 Entity를 가지고있어서 순환참조 문제가 발생 할 수 있는데요.
Entity반환하는 Controller의 경우에는 ResponseDto에 넣는방식으로 피하시기 바랍니당

**Comment by seunghyun333** [comment]
우아앙,,
제 숙제 끝내고 들어갈 것들이군요 
빠른 시일내에 끝내보겠습니다 ,,.,

**Comment by itkw87** [comment]
감사합니다. 종원님 
저도 빠른 시일내에 해보겠습니다!

**Comment by seunghyun333** [comment]
무슨 공부 하까요

**Comment by donsonioc2010** [comment]
@seunghyun333 이젠 스스로 찾아가야죠 크크킄
